name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Dispara o pipeline quando houver push na branch main
  workflow_dispatch:  # Permite acionar o pipeline manualmente

env:
  GCP_PROJECT: 'projeto-treinamento-450619'  # Nome do projeto no Google Cloud
  REGION: 'us-central1'                      # Região onde o serviço será implantado
  FUNCTION_NAME: 'cripto-app'                # Nome do serviço no Cloud Run
  MEMORY: '2Gi'                              # Memória alocada para o serviço

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Autenticar no Google Cloud
      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_CREDENTIALS }}
          gcloud config set project ${{ env.GCP_PROJECT }}

      # Instalar dependências do Python (se necessário)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Construir a imagem Docker e enviar para o Google Container Registry
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ env.GCP_PROJECT }}/${{ env.FUNCTION_NAME }} .
          docker push gcr.io/${{ env.GCP_PROJECT }}/${{ env.FUNCTION_NAME }}

      # Implantar no Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.FUNCTION_NAME }} \
            --image gcr.io/${{ env.GCP_PROJECT }}/${{ env.FUNCTION_NAME }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --memory ${{ env.MEMORY }} \
            --no-allow-unauthenticated \
            --timeout 300

      # Capturar a URL do serviço implantado
      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.FUNCTION_NAME }} --region ${{ env.REGION }} --format='value(status.url)')
          echo "Service URL: ${SERVICE_URL}"
